### ISSUE TITLE
Simplify the experience (My feedback)

### ISSUE THREAD

**Issue by Zorklis** [Littleozzz10/Continuum-Launcher#1]
Here's some feedback.
The launcher frontend itself? Looks great.
1.Continuum launcher and XL companion being in two separate folders is confusing and should be just in the same one.
2. The whole open config leaves a bad taste and I think should be scrapped/reworked.
3. Folders?? not sure how this works or it's just broken at the moment or where are they created because I keep making them and they are nowhere to be found. It's a complete mystery.
4. the folder delete button is broken, at first it wasn't and worked but now I have two folders (wherever they are) and the delete folder button shows up only if I make a third folder.
5. The layout / design could be better 
![image](https://github.com/Littleozzz10/Continuum-Launcher/assets/85455465/bd263710-6e13-41da-a1ba-b57e572ce40e)
6. the canary filepath should be a little lower, away from the other one, providing better spacing.
7. Ideally the game configuration setup itself would be done in the launcher instead of a second app.
8. Kinect Support, not really needed at the moment and just wastes space
9. Rename Artwork path to Cover path, much easier to understand. Plus it already says Cover preview on the bottom so it's more streamlined :)

About companion page.
![XLCompanion_akuP6yKCQP](https://github.com/Littleozzz10/Continuum-Launcher/assets/85455465/41309260-73a1-49f5-8104-dba1f3e85aed)
1. The title on the top is redundant since it says on the app window itself.
2. fix spelling "source avaiable" to "source available".

Thanks

**Comment by Littleozzz10** [comment]
I have made a few small changes regarding this feedback, and they are in the new 1.0.3 Beta 1 release. I unfortunately have not had a lot of time to put into side project like this, but am hopeful that in the future I can keep updating this launcher.

Regarding Folders, I changed the name in the new build to Categories, as it makes it more clear what they actually are. They do not create folders in Windows, but rather group together games in the Launcher itself. One of the changes I've been wanting to make to the Launcher itself is a way of making that more clear in the Launcher, as right now switching Categories requires the user to know they have to click the Category name at the top, unless they have a controller connected. In addition, I am aware that the Categories' functionality is buggy and Companion's ability to edit them doesn't always work. It is an issue I'm going to fix once I find the cause.

The Companion application was created since it was faster for me to put together a WinForms application than to implement all the required UI elements into the Launcher itself. The eventual goal is to move most, if not all, of Companion's functionality into the Launcher.

As always, all feedback is appreciated and I thank you! Apologies for the late update.
